---
apiVersion: v1
kind: Namespace
metadata:
  name: darkweb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: log4shell
  name: log4shell
  namespace: darkweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log4shell
  template:
    metadata:
      labels:
        app: log4shell
    spec:
      containers:
        - name: ldap
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "256Mi"
            requests:
              memory: "128Mi"
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: ldap
  namespace: darkweb
spec:
  selector:
    app: log4shell
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: evil
  namespace: darkweb
spec:
  selector:
    app: log4shell
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
  type: ClusterIP
